/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

data class User(val username: String, val friends: List<User> = emptyList())

class App {
    fun doLogin(username: String, password: String, callback: (User) -> Unit) {
        // Server request
        callback(User(username))
    }

    fun requestCurrentFriends(user: User, callback: (List<User>) -> Unit) {
        // Server request
        callback(listOf(User("1"), User("2")))
    }

    fun requestSuggestedFriends(user: User, callback: (List<User>) -> Unit) {
        // Server request
        callback(listOf(User("3"), User("4")))
    }
}

fun main() {
    val app = App()
    app.doLogin("username", "password") { user ->
        app.requestCurrentFriends(user) { friends ->
            app.requestSuggestedFriends(user) { suggestedFriends ->
                val userWithFriendsAndSuggestedFriends =
                    user.copy(friends = friends + suggestedFriends)
                println(userWithFriendsAndSuggestedFriends)
            }
        }
    }
}
